//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_Bot.Modules.Twitter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Credentials {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Credentials() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discord_Bot.Modules.Twitter.Credentials", typeof(Credentials).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3uBdSUv29Lz7I3Tjh0bBLQ5Qa.
        /// </summary>
        internal static string consumerKey {
            get {
                return ResourceManager.GetString("consumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kiZ3CpQstIWKT5HBXK6YXSY3CHGeyfnZYxTYh5mZyxatGxgBNg.
        /// </summary>
        internal static string consumerSecret {
            get {
                return ResourceManager.GetString("consumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1047719490287489024-dU18jaqLNMDX11p8WumvCIMA4EShA.
        /// </summary>
        internal static string userAccessSecret {
            get {
                return ResourceManager.GetString("userAccessSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7AhhYCjw9oSRTmg2V2QKGgjY1pfMyp0kdRa8r5FEHqjtR.
        /// </summary>
        internal static string userAccessToken {
            get {
                return ResourceManager.GetString("userAccessToken", resourceCulture);
            }
        }
    }
}
